/**
 * Mock data shaped exactly like the backend JSON contracts.
 * See: Architecture_MVP_Personalized_Learning_Path_Fusion_AI.pdf
 *
 * When the real backend is ready, this file becomes unused —
 * each service function swaps its `return MOCK_*` for a `fetch()` call.
 */

// ─── Students ────────────────────────────────────────────────────
export const MOCK_STUDENTS = [
  { student_code: "STD001", full_name: "Yassine El Amrani", email: "yassine@example.com", class_code: "L1-INFO-A", teacher_code: "T001" },
  { student_code: "STD002", full_name: "Amina Benali", email: "amina@example.com", class_code: "L1-INFO-A", teacher_code: "T001" },
  { student_code: "STD003", full_name: "Karim Idrissi", email: "karim@example.com", class_code: "L1-INFO-A", teacher_code: "T001" },
  { student_code: "STD004", full_name: "Fatima Zahra Ouali", email: "fatima@example.com", class_code: "L1-INFO-B", teacher_code: "T001" },
  { student_code: "STD005", full_name: "Omar Tazi", email: "omar@example.com", class_code: "L1-INFO-B", teacher_code: "T001" },
  { student_code: "STD006", full_name: "Salma Kettani", email: "salma@example.com", class_code: "L1-INFO-A", teacher_code: "T001" },
  { student_code: "STD007", full_name: "Mehdi Alaoui", email: "mehdi@example.com", class_code: "L1-INFO-B", teacher_code: "T001" },
  { student_code: "STD008", full_name: "Nadia Fassi", email: "nadia@example.com", class_code: "L1-INFO-A", teacher_code: "T001" },
];

// ─── Skills per student (WF-03 output shape) ────────────────────
export const MOCK_SKILL_RESULTS = {
  STD001: [
    { skill_result_id: 1001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 80, max_score: 100, percentage: 80, gap_level: "mastered" },
    { skill_result_id: 1002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 30, max_score: 100, percentage: 30, gap_level: "critical_gap" },
    { skill_result_id: 1003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 40, max_score: 100, percentage: 40, gap_level: "gap" },
    { skill_result_id: 1004, skill_code: "PY-LISTS", skill_name: "Lists", score: 70, max_score: 100, percentage: 70, gap_level: "mastered" },
    { skill_result_id: 1005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 55, max_score: 100, percentage: 55, gap_level: "fragile" },
  ],
  STD002: [
    { skill_result_id: 2001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 90, max_score: 100, percentage: 90, gap_level: "mastered" },
    { skill_result_id: 2002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 65, max_score: 100, percentage: 65, gap_level: "fragile" },
    { skill_result_id: 2003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 72, max_score: 100, percentage: 72, gap_level: "mastered" },
    { skill_result_id: 2004, skill_code: "PY-LISTS", skill_name: "Lists", score: 45, max_score: 100, percentage: 45, gap_level: "gap" },
    { skill_result_id: 2005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 80, max_score: 100, percentage: 80, gap_level: "mastered" },
  ],
  STD003: [
    { skill_result_id: 3001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 55, max_score: 100, percentage: 55, gap_level: "fragile" },
    { skill_result_id: 3002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 25, max_score: 100, percentage: 25, gap_level: "critical_gap" },
    { skill_result_id: 3003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 30, max_score: 100, percentage: 30, gap_level: "critical_gap" },
    { skill_result_id: 3004, skill_code: "PY-LISTS", skill_name: "Lists", score: 60, max_score: 100, percentage: 60, gap_level: "fragile" },
    { skill_result_id: 3005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 35, max_score: 100, percentage: 35, gap_level: "gap" },
  ],
  STD004: [
    { skill_result_id: 4001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 95, max_score: 100, percentage: 95, gap_level: "mastered" },
    { skill_result_id: 4002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 85, max_score: 100, percentage: 85, gap_level: "mastered" },
    { skill_result_id: 4003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 78, max_score: 100, percentage: 78, gap_level: "mastered" },
    { skill_result_id: 4004, skill_code: "PY-LISTS", skill_name: "Lists", score: 90, max_score: 100, percentage: 90, gap_level: "mastered" },
    { skill_result_id: 4005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 65, max_score: 100, percentage: 65, gap_level: "fragile" },
  ],
  STD005: [
    { skill_result_id: 5001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 40, max_score: 100, percentage: 40, gap_level: "gap" },
    { skill_result_id: 5002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 50, max_score: 100, percentage: 50, gap_level: "fragile" },
    { skill_result_id: 5003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 35, max_score: 100, percentage: 35, gap_level: "gap" },
    { skill_result_id: 5004, skill_code: "PY-LISTS", skill_name: "Lists", score: 60, max_score: 100, percentage: 60, gap_level: "fragile" },
    { skill_result_id: 5005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 45, max_score: 100, percentage: 45, gap_level: "gap" },
  ],
  STD006: [
    { skill_result_id: 6001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 75, max_score: 100, percentage: 75, gap_level: "mastered" },
    { skill_result_id: 6002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 70, max_score: 100, percentage: 70, gap_level: "mastered" },
    { skill_result_id: 6003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 60, max_score: 100, percentage: 60, gap_level: "fragile" },
    { skill_result_id: 6004, skill_code: "PY-LISTS", skill_name: "Lists", score: 85, max_score: 100, percentage: 85, gap_level: "mastered" },
    { skill_result_id: 6005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 72, max_score: 100, percentage: 72, gap_level: "mastered" },
  ],
  STD007: [
    { skill_result_id: 7001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 60, max_score: 100, percentage: 60, gap_level: "fragile" },
    { skill_result_id: 7002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 20, max_score: 100, percentage: 20, gap_level: "critical_gap" },
    { skill_result_id: 7003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 55, max_score: 100, percentage: 55, gap_level: "fragile" },
    { skill_result_id: 7004, skill_code: "PY-LISTS", skill_name: "Lists", score: 40, max_score: 100, percentage: 40, gap_level: "gap" },
    { skill_result_id: 7005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 30, max_score: 100, percentage: 30, gap_level: "critical_gap" },
  ],
  STD008: [
    { skill_result_id: 8001, skill_code: "PY-VARIABLES", skill_name: "Variables", score: 88, max_score: 100, percentage: 88, gap_level: "mastered" },
    { skill_result_id: 8002, skill_code: "PY-LOOPS", skill_name: "Loops", score: 75, max_score: 100, percentage: 75, gap_level: "mastered" },
    { skill_result_id: 8003, skill_code: "PY-FUNCTIONS", skill_name: "Functions", score: 82, max_score: 100, percentage: 82, gap_level: "mastered" },
    { skill_result_id: 8004, skill_code: "PY-LISTS", skill_name: "Lists", score: 70, max_score: 100, percentage: 70, gap_level: "mastered" },
    { skill_result_id: 8005, skill_code: "PY-LOGIC", skill_name: "Logic", score: 68, max_score: 100, percentage: 68, gap_level: "fragile" },
  ],
};

// ─── Student Results (ORCH-01 output shape) ─────────────────────
export const MOCK_STUDENT_RESULTS = {
  STD001: {
    student_id: 1, assessment_id: 1, student_result_id: 101,
    global_score: 55, gaps_detected: true, priority_level: "high",
    diagnosis_summary: "Good mastery of variables, critical difficulty with loops and weakness in functions.",
    diagnosis_strengths: "Variables, Lists",
    diagnosis_weaknesses: "Loops, Functions",
    pedagogical_impact: "Difficulty automating repetitive tasks and structuring reusable code.",
    priority_justification: "Immediate intervention required on loops.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "gaps_detected",
  },
  STD002: {
    student_id: 2, assessment_id: 1, student_result_id: 102,
    global_score: 70, gaps_detected: true, priority_level: "medium",
    diagnosis_summary: "Strong in variables and logic, needs support with lists.",
    diagnosis_strengths: "Variables, Logic, Functions",
    diagnosis_weaknesses: "Lists",
    pedagogical_impact: "Limited ability to handle data collections.",
    priority_justification: "Moderate support recommended.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "gaps_detected",
  },
  STD003: {
    student_id: 3, assessment_id: 1, student_result_id: 103,
    global_score: 41, gaps_detected: true, priority_level: "high",
    diagnosis_summary: "Multiple critical gaps across loops, functions, and logic.",
    diagnosis_strengths: "None significant",
    diagnosis_weaknesses: "Loops, Functions, Logic",
    pedagogical_impact: "Fundamental programming concepts not yet acquired.",
    priority_justification: "Urgent multi-skill intervention needed.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "gaps_detected",
  },
  STD004: {
    student_id: 4, assessment_id: 1, student_result_id: 104,
    global_score: 83, gaps_detected: false, priority_level: "standard",
    diagnosis_summary: "Excellent overall mastery with minor fragility in logic.",
    diagnosis_strengths: "Variables, Loops, Functions, Lists",
    diagnosis_weaknesses: "Logic (fragile)",
    pedagogical_impact: "Minor reinforcement needed.",
    priority_justification: "Standard follow-up sufficient.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "no_significant_gaps",
  },
  STD005: {
    student_id: 5, assessment_id: 1, student_result_id: 105,
    global_score: 46, gaps_detected: true, priority_level: "high",
    diagnosis_summary: "Widespread difficulties across variables, functions, and logic.",
    diagnosis_strengths: "None significant",
    diagnosis_weaknesses: "Variables, Functions, Logic",
    pedagogical_impact: "Cannot build functional programs independently.",
    priority_justification: "Urgent intervention required.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "gaps_detected",
  },
  STD006: {
    student_id: 6, assessment_id: 1, student_result_id: 106,
    global_score: 72, gaps_detected: false, priority_level: "low",
    diagnosis_summary: "Good overall performance, functions slightly fragile.",
    diagnosis_strengths: "Variables, Loops, Lists, Logic",
    diagnosis_weaknesses: "Functions (fragile)",
    pedagogical_impact: "Minor reinforcement on function design.",
    priority_justification: "Low priority, monitoring sufficient.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "no_significant_gaps",
  },
  STD007: {
    student_id: 7, assessment_id: 1, student_result_id: 107,
    global_score: 41, gaps_detected: true, priority_level: "high",
    diagnosis_summary: "Critical gaps in loops and logic, general weakness.",
    diagnosis_strengths: "Variables (fragile)",
    diagnosis_weaknesses: "Loops, Lists, Logic",
    pedagogical_impact: "Unable to construct loop-based algorithms.",
    priority_justification: "Immediate multi-topic support needed.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "gaps_detected",
  },
  STD008: {
    student_id: 8, assessment_id: 1, student_result_id: 108,
    global_score: 77, gaps_detected: false, priority_level: "low",
    diagnosis_summary: "Strong overall, logic slightly below mastery threshold.",
    diagnosis_strengths: "Variables, Loops, Functions, Lists",
    diagnosis_weaknesses: "Logic (fragile)",
    pedagogical_impact: "Minimal impact on programming ability.",
    priority_justification: "Standard monitoring.",
    confidence: "high", model_name: "gemini-flash-lite",
    analysis_status: "no_significant_gaps",
  },
};

// ─── Learning Plans (ORCH-02 / WF-06 output shape) ─────────────
export const MOCK_LEARNING_PLANS = [
  {
    learning_plan_id: 201, plan_code: "PLAN-STD001-PYTHON", student_result_id: 101,
    version: 1, duration_days: 7,
    plan_title: "Python Loops & Functions Reinforcement",
    objective_summary: "Strengthen mastery of loops and functions through targeted practice.",
    success_criteria_summary: "Achieve at least 65% on loops and 60% on functions.",
    status: "in_progress", teacher_decision: "approve",
    teacher_comment: "Well-structured plan, approved.",
    completion_rate: 50, notification_status: "sent",
    student_code: "STD001", student_name: "Yassine El Amrani",
    subject: "Python", priority_level: "high", global_score: 55,
  },
  {
    learning_plan_id: 202, plan_code: "PLAN-STD002-PYTHON", student_result_id: 102,
    version: 1, duration_days: 5,
    plan_title: "Python Lists Mastery Program",
    objective_summary: "Build solid list manipulation and comprehension skills.",
    success_criteria_summary: "Score at least 65% on lists assessment.",
    status: "pending_teacher_validation", teacher_decision: null,
    teacher_comment: null,
    completion_rate: 0, notification_status: null,
    student_code: "STD002", student_name: "Amina Benali",
    subject: "Python", priority_level: "medium", global_score: 70,
  },
  {
    learning_plan_id: 203, plan_code: "PLAN-STD003-PYTHON", student_result_id: 103,
    version: 2, duration_days: 7,
    plan_title: "Comprehensive Python Fundamentals Recovery",
    objective_summary: "Address critical gaps in loops, functions, and logic.",
    success_criteria_summary: "Achieve passing scores (50%+) on all three weak skills.",
    status: "pending_teacher_validation", teacher_decision: null,
    teacher_comment: null,
    completion_rate: 0, notification_status: null,
    student_code: "STD003", student_name: "Karim Idrissi",
    subject: "Python", priority_level: "high", global_score: 41,
  },
  {
    learning_plan_id: 204, plan_code: "PLAN-STD005-PYTHON", student_result_id: 105,
    version: 1, duration_days: 7,
    plan_title: "Python Core Skills Recovery",
    objective_summary: "Build foundational understanding of variables, functions, and logic.",
    success_criteria_summary: "Achieve at least 55% on each weak skill.",
    status: "approved", teacher_decision: "approve",
    teacher_comment: "Good plan. Proceed with sending.",
    completion_rate: 0, notification_status: null,
    student_code: "STD005", student_name: "Omar Tazi",
    subject: "Python", priority_level: "high", global_score: 46,
  },
  {
    learning_plan_id: 205, plan_code: "PLAN-STD007-PYTHON", student_result_id: 107,
    version: 1, duration_days: 7,
    plan_title: "Loops & Logic Intensive Program",
    objective_summary: "Focus on critical gaps in loops and logic foundations.",
    success_criteria_summary: "Achieve 50% on loops and 45% on logic.",
    status: "sent", teacher_decision: "approve",
    teacher_comment: "Approved with emphasis on loop exercises.",
    completion_rate: 25, notification_status: "sent",
    student_code: "STD007", student_name: "Mehdi Alaoui",
    subject: "Python", priority_level: "high", global_score: 41,
  },
  {
    learning_plan_id: 206, plan_code: "PLAN-STD003-PYTHON-V1", student_result_id: 103,
    version: 1, duration_days: 7,
    plan_title: "Python Fundamentals Recovery (V1)",
    objective_summary: "Initial plan addressing loops and functions.",
    success_criteria_summary: "Achieve 50%+ on loops and functions.",
    status: "rejected", teacher_decision: "reject",
    teacher_comment: "Plan does not address logic gaps. Please regenerate.",
    completion_rate: 0, notification_status: null,
    student_code: "STD003", student_name: "Karim Idrissi",
    subject: "Python", priority_level: "high", global_score: 41,
  },
];

// ─── Learning Plan Activities (learning_plan_activities table) ──
export const MOCK_ACTIVITIES = {
  201: [
    {
      id: 301, learning_plan_id: 201, activity_order: 1,
      skill_code: "PY-LOOPS", resource_code: "RES-LOOPS-01",
      title: "Introduction to For Loops", instruction: "Watch the video and complete practice exercises.",
      resource_url: "https://example.com/loops-intro", resource_type: "video",
      estimated_minutes: 15, target_score: 50,
      activity_status: "completed", completion_percentage: 100, completed_at: "2026-07-14T10:00:00Z",
    },
    {
      id: 302, learning_plan_id: 201, activity_order: 2,
      skill_code: "PY-LOOPS", resource_code: "RES-LOOPS-02",
      title: "Loop Patterns & Nested Loops", instruction: "Complete the interactive coding exercises.",
      resource_url: "https://example.com/loops-patterns", resource_type: "exercise",
      estimated_minutes: 30, target_score: 65,
      activity_status: "in_progress", completion_percentage: 60, completed_at: null,
    },
    {
      id: 303, learning_plan_id: 201, activity_order: 3,
      skill_code: "PY-FUNCTIONS", resource_code: "RES-FUNC-01",
      title: "Creating Python Functions", instruction: "Read the guide and write 5 practice functions.",
      resource_url: "https://example.com/functions-guide", resource_type: "article",
      estimated_minutes: 25, target_score: 55,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
    {
      id: 304, learning_plan_id: 201, activity_order: 4,
      skill_code: "PY-FUNCTIONS", resource_code: "RES-FUNC-02",
      title: "Functions with Parameters & Return", instruction: "Complete the function challenge set.",
      resource_url: "https://example.com/functions-challenge", resource_type: "exercise",
      estimated_minutes: 30, target_score: 60,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
  ],
  202: [
    {
      id: 305, learning_plan_id: 202, activity_order: 1,
      skill_code: "PY-LISTS", resource_code: "RES-LISTS-01",
      title: "List Operations Fundamentals", instruction: "Study list creation, indexing, and slicing.",
      resource_url: "https://example.com/lists-basics", resource_type: "video",
      estimated_minutes: 20, target_score: 60,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
    {
      id: 306, learning_plan_id: 202, activity_order: 2,
      skill_code: "PY-LISTS", resource_code: "RES-LISTS-02",
      title: "List Comprehensions", instruction: "Practice writing list comprehensions.",
      resource_url: "https://example.com/list-comprehensions", resource_type: "exercise",
      estimated_minutes: 25, target_score: 65,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
  ],
  203: [
    {
      id: 307, learning_plan_id: 203, activity_order: 1,
      skill_code: "PY-LOOPS", resource_code: "RES-LOOPS-01",
      title: "Loop Fundamentals Review", instruction: "Rewatch the loops introduction and take notes.",
      resource_url: "https://example.com/loops-intro", resource_type: "video",
      estimated_minutes: 15, target_score: 45,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
    {
      id: 308, learning_plan_id: 203, activity_order: 2,
      skill_code: "PY-FUNCTIONS", resource_code: "RES-FUNC-01",
      title: "Functions Basics", instruction: "Complete the functions tutorial.",
      resource_url: "https://example.com/functions-guide", resource_type: "article",
      estimated_minutes: 25, target_score: 50,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
    {
      id: 309, learning_plan_id: 203, activity_order: 3,
      skill_code: "PY-LOGIC", resource_code: "RES-LOGIC-01",
      title: "Boolean Logic & Conditions", instruction: "Study boolean operators and conditional statements.",
      resource_url: "https://example.com/logic-basics", resource_type: "video",
      estimated_minutes: 20, target_score: 50,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
  ],
  204: [
    {
      id: 310, learning_plan_id: 204, activity_order: 1,
      skill_code: "PY-VARIABLES", resource_code: "RES-VAR-01",
      title: "Variable Types Deep Dive", instruction: "Review variable types and naming conventions.",
      resource_url: "https://example.com/variables", resource_type: "article",
      estimated_minutes: 15, target_score: 55,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
    {
      id: 311, learning_plan_id: 204, activity_order: 2,
      skill_code: "PY-FUNCTIONS", resource_code: "RES-FUNC-01",
      title: "Function Design Patterns", instruction: "Learn to write reusable functions.",
      resource_url: "https://example.com/functions-guide", resource_type: "article",
      estimated_minutes: 25, target_score: 55,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
  ],
  205: [
    {
      id: 312, learning_plan_id: 205, activity_order: 1,
      skill_code: "PY-LOOPS", resource_code: "RES-LOOPS-01",
      title: "Loops from Scratch", instruction: "Complete introductory loop exercises.",
      resource_url: "https://example.com/loops-intro", resource_type: "exercise",
      estimated_minutes: 20, target_score: 40,
      activity_status: "completed", completion_percentage: 100, completed_at: "2026-07-15T14:00:00Z",
    },
    {
      id: 313, learning_plan_id: 205, activity_order: 2,
      skill_code: "PY-LOGIC", resource_code: "RES-LOGIC-01",
      title: "Logic Foundations", instruction: "Study boolean logic and practice conditions.",
      resource_url: "https://example.com/logic-basics", resource_type: "video",
      estimated_minutes: 20, target_score: 40,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
    {
      id: 314, learning_plan_id: 205, activity_order: 3,
      skill_code: "PY-LOOPS", resource_code: "RES-LOOPS-02",
      title: "Advanced Loop Challenges", instruction: "Solve intermediate loop problems.",
      resource_url: "https://example.com/loops-patterns", resource_type: "exercise",
      estimated_minutes: 30, target_score: 50,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
  ],
  206: [
    {
      id: 315, learning_plan_id: 206, activity_order: 1,
      skill_code: "PY-LOOPS", resource_code: "RES-LOOPS-01",
      title: "Loop Basics", instruction: "Watch introductory video.",
      resource_url: "https://example.com/loops-intro", resource_type: "video",
      estimated_minutes: 15, target_score: 45,
      activity_status: "not_started", completion_percentage: 0, completed_at: null,
    },
  ],
};

// ─── Dashboard Data (WF-12 output shape) ────────────────────────
export const MOCK_DASHBOARD = {
  summary: {
    students_evaluated: 25,
    students_with_gaps: 18,
    critical_students: 6,
    plans_generated: 18,
    plans_pending_validation: 4,
    plans_approved: 12,
    plans_sent: 10,
    plans_completed: 2,
    average_progress: 42,
  },
  priority_distribution: {
    standard: 7,
    low: 3,
    medium: 9,
    high: 6,
  },
  plan_status_distribution: {
    generated: 2,
    pending_teacher_validation: 4,
    approved: 2,
    sent: 5,
    in_progress: 3,
    completed: 2,
  },
  skill_gap_distribution: [
    { skill_code: "PY-LOOPS", skill_name: "Loops", students_count: 12, average_score: 38 },
    { skill_code: "PY-FUNCTIONS", skill_name: "Functions", students_count: 9, average_score: 45 },
    { skill_code: "PY-LOGIC", skill_name: "Logic", students_count: 7, average_score: 48 },
    { skill_code: "PY-LISTS", skill_name: "Lists", students_count: 5, average_score: 52 },
    { skill_code: "PY-VARIABLES", skill_name: "Variables", students_count: 3, average_score: 58 },
  ],
  students: [
    { student_code: "STD001", student_name: "Yassine El Amrani", global_score: 55, main_gap: "Loops", priority_level: "high", plan_status: "in_progress", completion_rate: 50 },
    { student_code: "STD002", student_name: "Amina Benali", global_score: 70, main_gap: "Lists", priority_level: "medium", plan_status: "pending_teacher_validation", completion_rate: 0 },
    { student_code: "STD003", student_name: "Karim Idrissi", global_score: 41, main_gap: "Loops", priority_level: "high", plan_status: "pending_teacher_validation", completion_rate: 0 },
    { student_code: "STD004", student_name: "Fatima Zahra Ouali", global_score: 83, main_gap: "Logic", priority_level: "standard", plan_status: null, completion_rate: null },
    { student_code: "STD005", student_name: "Omar Tazi", global_score: 46, main_gap: "Variables", priority_level: "high", plan_status: "approved", completion_rate: 0 },
    { student_code: "STD006", student_name: "Salma Kettani", global_score: 72, main_gap: "Functions", priority_level: "low", plan_status: null, completion_rate: null },
    { student_code: "STD007", student_name: "Mehdi Alaoui", global_score: 41, main_gap: "Loops", priority_level: "high", plan_status: "sent", completion_rate: 25 },
    { student_code: "STD008", student_name: "Nadia Fassi", global_score: 77, main_gap: "Logic", priority_level: "low", plan_status: null, completion_rate: null },
  ],
};
